### ISSUE TITLE
ntpmon should support configuration for path to chronyc binary/chrony configs

### ISSUE THREAD

**Issue by afreiberger** [paulgear/ntpmon#13]
Related to the issues noted in https://bugs.launchpad.net/ntp-charm/+bug/1938721 with the co-resident installation of ntp-charm and snap installed MAAS, it would be useful to have the ability to define or detect alternate paths to the chrony client.

Path for snap installed MAAS chrony client is: /snap/maas/current/usr/bin/chronyc

**Comment by paulgear** [comment]
NTPmon doesn't hard-code paths of binaries, but accepts the system `PATH` setting.  If a non-default `chronyc` is required, please set `PATH` appropriately in the environment, e.g. via `/etc/default/ntpmon` if installed with the existing PPA Debian package, or whatever `EnvironmentFile` is set to in your `systemd` service file.
