### ISSUE TITLE
How to install/run this program

### ISSUE THREAD

**Issue by faircm2** [paulgear/ntpmon#15]
I could not make out from the documentation how to install and run this program? Basic question.

**Comment by paulgear** [comment]
Hi @faircm2 - very sorry I didn't see this before.  I'm not sure what has happened to my notification settings.  I'll update the README shortly to fix this, but just `./src/ntpmon.py` from the checked-out source should work, once the prerequisites are installed.  There's also an example of starting it in telegraf mode in `src/ntpmon-telegraf.systemd`.

However, this does need to be much better and I'll work on getting an install script set up sometime in the not-too-distant future.
